version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\WhySoSerial
image:
  - Visual Studio 2017
configuration:
  - Release
platform:
  - x64
environment:
  matrix:
    - arch: Win64
matrix:
  fast_finish: true

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - vcpkg install fltk

build_script:
  - cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=c:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake -G "Visual Studio 15 2017 Win64" ../
  - cmake --build . --config Release
