version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\WhySoSerial
image:
  - Visual Studio 2017
configuration:
  - Release
platform:
  - x64
environment:
  matrix:
    - arch: Win64
matrix:
  fast_finish: true
init:
- ps: new-itemproperty -path "HKLM:\SOFTWARE\Microsoft\.NETFramework\v4.0.30319" -name "SchUseStrongCrypto" -Value 1 -PropertyType "DWord";
- ps: new-itemproperty -path "HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NETFramew

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - vcpkg install fltk:x64-windows
  - vcpkg integrate install

build_script:
  - cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=c:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake -G "Visual Studio 15 2017 Win64" ../
  - cmake --build . --config Release
